Fix PowerShell linking for AMD64 builds
laravel/settler pull request #243
Opened 2022-11-11 11:58 UTC by mnightingale

Trying to do my own VMWare build on Windows, but it always links the arm script.

I've copied the logic from `link-to-bento.sh`, but I've only kept the find/replaces that were already present.
I have updated the values to mirror the .sh ones though, memory 2084 to 2048, disk_size 131072 to 524288

Also used `Set-Content -NoNewLine` to stop adding new lines to end of the output.

13.x branch will need similar but it looks like it also uses a boot_wait replacement.

2022-11-11 20:19 UTC, svpernova09 requested changes
Looking good, but we'll want the disk size to be `131072`.

2022-11-13 10:57 UTC, mnightingale commented
I've changed the disk_size back, although I'm unclear why `link-to-bento.ps1` and `link-to-bento.sh` would set different values.

2023-01-11 13:50 UTC, mnightingale commented
It was time to make a 13.0.0 vmware build so rebased.

Two commits, first just copies as homestead.sh and homestead-arm.sh and adds arm changes.
Second adds -NoNewLine to each Set-Content so it doesn't add newlines to the end of the file.

2023-01-14 16:18 UTC, svpernova09 approved these changes
Thanks!

2023-01-14 16:18 UTC, merged